export const DASHBOARD_STATS_REQUEST = 'DASHBOARD_STATS_REQUEST'
export const DASHBOARD_STATS_SUCCESS = 'DASHBOARD_STATS_SUCCESS'
export const DASHBOARD_STATS_FAILURE = 'DASHBOARD_STATS_FAILURE'

export const DASHBOARD_SALES_DATA_REQUEST = 'DASHBOARD_SALES_DATA_REQUEST'
export const DASHBOARD_SALES_DATA_SUCCESS = 'DASHBOARD_SALES_DATA_SUCCESS'
export const DASHBOARD_SALES_DATA_FAILURE = 'DASHBOARD_SALES_DATA_FAILURE'
