// orderConstants.js
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_USER_REQUEST = 'ORDER_USER_REQUEST';
export const ORDER_USER_SUCCESS = 'ORDER_USER_SUCCESS';
export const ORDER_USER_FAIL = 'ORDER_USER_FAIL';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

export const ORDER_DAILY_REQUEST = 'ORDER_DAILY_REQUEST';
export const ORDER_DAILY_SUCCESS = 'ORDER_DAILY_SUCCESS';
export const ORDER_DAILY_FAIL = 'ORDER_DAILY_FAIL';

export const ORDER_SUMMARY_REQUEST = 'ORDER_SUMMARY_REQUEST';
export const ORDER_SUMMARY_SUCCESS = 'ORDER_SUMMARY_SUCCESS';
export const ORDER_SUMMARY_FAIL = 'ORDER_SUMMARY_FAIL';

export const SALES_DATA_REQUEST = 'SALES_DATA_REQUEST';
export const SALES_DATA_SUCCESS = 'SALES_DATA_SUCCESS';
export const SALES_DATA_FAIL = 'SALES_DATA_FAIL';
