// orderConstants.js
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';



export const ORDER_CANCEL_REQUEST='ORDER_CANCEL_REQUEST'
export const ORDER_CANCEL_SUCCESS='ORDER_CANCEL_SUCCESS'
export const ORDER_CANCEL_FAIL='ORDER_CANCEL_FAIL'

export const COUPON_VALIDATE_REQUEST='COUPON_VALIDATE_REQUEST'
export const COUPON_VALIDATE_SUCCESS='COUPON_VALIDATE_SUCCESS'
export const COUPON_VALIDATE_FAIL='COUPON_VALIDATE_FAIL'
